/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, Record<string, any>> = {
  "wuhan": {
    "hello-world": {
      name: "hello-world",
      description: "A simple hello world component",
      type: "registry:component",
      registryDependencies: ["button"],
      files: [{
        path: "registry/wuhan/blocks/hello-world/hello-world.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/blocks/hello-world/hello-world.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "hello-world"
        return { default: mod.default || mod[exportName] }
      }),
      categories: [],
      meta: {},
    },
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: [],
      files: [{
        path: "registry/wuhan/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/ui/button.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button"
        return { default: mod.default || mod[exportName] }
      }),
      categories: [],
      meta: {},
    },
    "textarea": {
      name: "textarea",
      description: "",
      type: "registry:ui",
      registryDependencies: [],
      files: [{
        path: "registry/wuhan/ui/textarea.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/ui/textarea.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "textarea"
        return { default: mod.default || mod[exportName] }
      }),
      categories: [],
      meta: {},
    },
    "prompt-01": {
      name: "prompt-01",
      description: "A simple prompt.",
      type: "registry:block",
      registryDependencies: ["textarea","button"],
      files: [{
        path: "registry/wuhan/blocks/prompt-01.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/blocks/prompt-01.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "prompt-01"
        return { default: mod.default || mod[exportName] }
      }),
      categories: [],
      meta: {},
    },
    "prompt-default": {
      name: "prompt-default",
      description: "",
      type: "registry:example",
      registryDependencies: ["textarea","button"],
      files: [{
        path: "registry/wuhan/examples/prompt-default.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/examples/prompt-default.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "prompt-default"
        return { default: mod.default || mod[exportName] }
      }),
      categories: [],
      meta: {},
    },
    "prompt-active": {
      name: "prompt-active",
      description: "",
      type: "registry:example",
      registryDependencies: ["textarea","button"],
      files: [{
        path: "registry/wuhan/examples/prompt-active.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/examples/prompt-active.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "prompt-active"
        return { default: mod.default || mod[exportName] }
      }),
      categories: [],
      meta: {},
    },
    "prompt-disabled": {
      name: "prompt-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["textarea","button"],
      files: [{
        path: "registry/wuhan/examples/prompt-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/examples/prompt-disabled.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "prompt-disabled"
        return { default: mod.default || mod[exportName] }
      }),
      categories: [],
      meta: {},
    },
    "prompt-composed-demo": {
      name: "prompt-composed-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["prompt-01","textarea","button"],
      files: [{
        path: "registry/wuhan/examples/prompt-composed-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/examples/prompt-composed-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "prompt-composed-demo"
        return { default: mod.default || mod[exportName] }
      }),
      categories: [],
      meta: {},
    },
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/wuhan/examples/button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/examples/button-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-demo"
        return { default: mod.default || mod[exportName] }
      }),
      categories: [],
      meta: {},
    },
    "textarea-demo": {
      name: "textarea-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["textarea"],
      files: [{
        path: "registry/wuhan/examples/textarea-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/examples/textarea-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "textarea-demo"
        return { default: mod.default || mod[exportName] }
      }),
      categories: [],
      meta: {},
    },
    "prompt-demo": {
      name: "prompt-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["prompt-01","textarea","button"],
      files: [{
        path: "registry/wuhan/examples/prompt-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/examples/prompt-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "prompt-demo"
        return { default: mod.default || mod[exportName] }
      }),
      categories: [],
      meta: {},
    },
  },
}